### ISSUE TITLE
Any possibility to create a DID from an existing key?

### ISSUE THREAD

**Issue by kuhlmannmarkus** [decentralized-identity/ion-tools#18]
I would like to have the possibility to create a DID document from an existing key that I can save somewhere in the form of an mneminic or equivalent. At least it would be nice to be able to export the root keys to form an mnemonic after creating a DID document. Otherwise I would not know how to be able to recover access to my DID in the case of a data loss or something else.

**Comment by ankit90anand** [comment]
ION DID accepts public key in JWK format.

If you looking for a way to convert keys from one format to another then https://github.com/panva/jose may be useful.

**Comment by chrisgem** [comment]
@ankianan can you please provide an example? I've tried providing the public key a few different ways and the DID is always different.

**Comment by ankianan** [comment]
DID is just an identifier to DID Document stored on public ledger. 

Each DID document can express cryptographic material, verification methods, or service endpoints, which provide a set of mechanisms enabling a DID controller to prove control of the DID. 

DID is not a function of public key but just a reference to it.

**Comment by kuhlmannmarkus** [comment]
Hi @ankianan, thanks for your answer.
But I still cannot wrap my head around what I should do, to make an identity recoverable. The creation of an identity should be based on some private key and only the owner of this private key should be allowed/abled to commit changes to the corresponding DID document. I need a way to generate an identity based on key material that is a priori existent. Mainly for the purpose of giving users a backup and recovery option.
Thanks

**Comment by ankianan** [comment]
“ The creation of an identity should be based on some private key and only the owner of this private key should be allowed/abled to commit changes to the corresponding DID document.”

https://github.com/decentralized-identity/ion/blob/master/docs/Q-and-A.md#q-who-owns-the-dids-generated-with-ion


“ I need a way to generate an identity based on key material that is a priori existent. Mainly for the purpose of giving users a backup and recovery option.”

I am planning to explore this.
https://www.investopedia.com/terms/h/hd-wallet-hierarchical-deterministic-wallet.asp

HD wallets enable a series of key pairs to be created from one random seed, providing convenience and manageability as well as high-level security.

**Comment by monkins1010** [comment]
> Hi @ankianan, thanks for your answer. But I still cannot wrap my head around what I should do, to make an identity recoverable. The creation of an identity should be based on some private key and only the owner of this private key should be allowed/abled to commit changes to the corresponding DID document. I need a way to generate an identity based on key material that is a priori existent. Mainly for the purpose of giving users a backup and recovery option. Thanks

Looking at newer ID technology, there is a way to have a Decentralized ID that you own (and don't rent), and the private keys that are associated with the ID are the spend/sign keys / revoking keys / recovering keys (which can be recovered to a new set if lost).  This way you can use the ID to sign in to systems and apps, sign attestations etc.  If the private keys change that control the ID, the systems that use it do not care as they automatically upgrade when you change the keys) 

If you want to sell that ID e.g. if the ID owned a company you could sell the ID on an open marketplace on chain, using no other system than the on chain marketplace. This is the future of ID with advanced functions of the ID actually being a crypto primitive ( an actual wallet to hold crypto, a root source of a token, root source of a blockchain , ZK transactions, an NFT).

Cheers
