### ISSUE TITLE
Updating a DID document

### ISSUE THREAD

**Issue by eth4n** [decentralized-identity/ion-tools#24]
Hello,

I was trying to play around with this library to create and updating a DID and stumbled upon some issues:
1) Example to instantiate a new DID object and creating the DID document uses the full DID document's content - so far this makes sense for the create usecase. What is/should be the procedure to instantiating a DID object for an existing DID? E.g. the DID I created yesterday? new ION.DID('did:ion:XXX') does not work as a content array is expected. 

2) How to update an existing DID document using this repository? I failed to find in the documentation how to apply the private key to sign off the update operation. Tried to check your lib's code and used option.signer to provide the key and the resulting update operation was signed, send, and accepted by the ION node (beta.ion.msidentity). But I do not see the changes in the DID document applied (but I can't find a spot on how to check about submitted operations state). 
Is there a working example on how to update? The readme does not state the source of private key (only new ION.DID({...}) )

Thanks in advance

**Comment by Lisztos** [comment]
Did you manage to update an existing DID?
