### ISSUE TITLE
Storing BBS keys in DID

### ISSUE THREAD

**Issue by vongohren** [decentralized-identity/ion-tools#4]
Is it straight forward in storing BBS keys in the did, as we have access to the json object itself for public key?
Or does it happen any checks of verifications on the creation that will stop it?

Considering to combine this, and BBS: https://w3c-ccg.github.io/ldp-bbs2020/ --- https://github.com/mattrglobal/node-bbs-signatures with https://github.com/mattrglobal/jsonld-signatures-bbs to build out ION dids with multi proof VCs.

But if I use ion did, with public keys as the bbs spec says how to use it, and use the # sign to point to keys, I guess it can be resolved in a nice manner?

**Comment by csuwildcat** [comment]
You can put any type of key in your DID Document, so long as it is in JWK format

**Comment by vongohren** [comment]
@csuwildcat thanks for the update, will close this then!
