### ISSUE TITLE
signJws is not a constructor

### ISSUE THREAD

**Issue by vongohren** [decentralized-identity/ion-tools#6]
Doing what the documentation says, fails. 
<img width="1680" alt="Screen Shot 2021-04-03 at 17 29 49" src="https://user-images.githubusercontent.com/1012055/113483182-6da3db80-94a2-11eb-9791-d0049562955f.png">
Changing it to await and call the function works.
<img width="1680" alt="Screen Shot 2021-04-03 at 17 30 53" src="https://user-images.githubusercontent.com/1012055/113483184-709ecc00-94a2-11eb-9ecf-d14b4402a590.png">

What is expected behaviour? Should I change the docs?

**Comment by csuwildcat** [comment]
The sign/verify JWS methods are static singleton functions: https://github.com/decentralized-identity/ion-tools#ionsignjwsparams, not classes. (is there somewhere in the docs that suggests they are a class?)

**Comment by vongohren** [comment]
@csuwildcat I guess this commit answers your question: https://github.com/decentralized-identity/ion-tools/commit/ea858539ffe5e1888e9f090edd34243eedf3ad60

You can close this when have seen this
